### ISSUE TITLE
Suggestion: can we have github links added to milestone projects?

### ISSUE THREAD

**Issue by M2kishore** [DjangoForAll/Django-Course#2]
I am starting to love the content! and I have some suggestions.
It felt easier to fork the repository rather than downloading the zip and working on it.
It is a friendly suggestion from my end

**Comment by vigneshhari** [comment]
This was purposefully removed since we can easily view forked repo's right away! The first instinct to view solutions before actually attempting the problem is removed.
You can fork them if you want to!
